### PR TITLE
Use HeaderLength when parsing mobi header.

### LINKED ISSUE #5: Opening mobi file causes high CPU / memory usage indefinitely
When trying to open a specific mobi file to read the metadata, the program maxes out an entire core of CPU usage and the RAM usage grows continuously, by >400MB per minute (reaching 1GB+ of RAM usage for a 2MB book in about 3 minutes, and I did not see the program exit), which makes it seem like this is a decompression error. On Windows, Calibre and SumatraPDF open the book without issue.

I can send a copy of the MOBI by email (to avoid issues with uploading it to a public website).

A minimal code example needed to reproduce the issue (at least on Windows and Ubuntu in WSL):

```rust
use mobi::Mobi;

fn main() -> Result<(), ()> {
    let doc = match Mobi::from_path("books/All Systems Red - Martha Wells.mobi") {
        Err(_) => return Ok(()),
        Ok(d) => d,
    };
    Ok(())
}
```

The program is run with `cargo run --release`.

### PR DESCRIPTION
**Pull request by philippeitis**
Its possible for the mobi header to be a length other than 232, and have padding bytes of 0xFFFF_FFFF at the end. The previous assumption that this wasn't possible caused a bug where parsing the exth data would read these padding bytes 0xFFFF_FFFF - and then the program would try to read 4GB of data from the mobi.

This PR changes ExtHeader::parse to take the header_len and ExtHeader::get_records to take an offset to find the EXTH header.
A few other stylistic changes are included (which should hopefully make things easier to work with).

I have also simplified lz77.rs to avoid using Cursor - which allows us to return a `Vec<u8>` instead of an  `io::Error<Vec<u8>>`  and prevents unexpected errors.

This resolves #5, and at least for me, makes all of my mobi files open correctly.

As an additional note, since this crate is provided as a library, it would be nice if parsing the headers returned errors for unexpected / problematic values, since this would help make identifying malformed headers a lot easier (and would make this library a lot safer to use in other applications). For instance, testing that the record lengths are correct (no longer than the file length and at least 8 elements long), or that the EXTH identifier is always EXTH would have been helpful when debugging this specific problem, and I imagine it would make future issues a lot easier to resolve.

### CODE REVIEW

**Comment by wojciechkepka** [comment]
So I was getting index out of bounds when I tried this sample code with the book you sent me or with any book i tried to open.
```rust
  use mobi::Mobi;
  use std::env;
  fn main() -> Result<(), std::io::Error> {
      let m = Mobi::from_path(env::args().skip(1).take(1).next().expect("Missing argument"))?;
      Ok(())
  }
```

```
❯ RUST_BACKTRACE=1 ./target/release/mobi ~/dev/rust/mobi-rs/example.mobi
thread 'main' panicked at 'index out of bounds: the len is 30 but the index is 33', src/lz77.rs:30:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic_bounds_check
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:62
   3: mobi::lz77::decompress_lz77
   4: mobi::record::Record::parse_records
   5: mobi::Mobi::from_reader
   6: mobi::Mobi::from_path
   7: mobix::main
```

What fixed it is checking if the offset is within the bounds of text not the data length. I will display it below.

File: src/lz77.rs [hunk 1]
```diff
@@ -28,18 +24,18 @@ pub fn decompress_lz77(data: &[u8]) -> io::Result<Vec<u8>> {
             0x80..=0xbf => {
                 offset += 1;
                 if offset > length {
```
Comment (wojciechkepka) [inline src/lz77.rs:26]: This should check if the offset is within the text bounds not data. So changing this to `text.len()` fixes index out of bound for me.

File: src/headers/exth.rs [hunk 2]
```diff
@@ -39,50 +38,53 @@ pub struct ExtHeader {
     pub record_count: u32,
     pub records: HashMap<u32, String>,
 }
+
 impl ExtHeader {
     /// Parse a EXTH header from the content
-    pub(crate) fn parse(mut reader: &mut Reader) -> io::Result<ExtHeader> {
+    pub(crate) fn parse_no_hint(mut reader: &mut Reader) -> io::Result<ExtHeader> {
+        ExtHeader::parse(reader, 232)
```
Comment (wojciechkepka) [inline src/headers/exth.rs:45]: I would probably assign 232 to a const variable for readability as it is used in more than one place.

Comment (wojciechkepka) [reply src/headers/exth.rs:45]: Do you have an idea for a fitting name?

Comment (philippeitis) [reply src/headers/exth.rs:45]: I would go with DEFAULT_EXTH_OFFSET, but I get the impression that the main issue is the RECORDS_OFFSET - it seems like RECORDS_OFFSET should be 340 - 232, and we should pass the header length to populate_records()

Comment (philippeitis) [reply src/headers/exth.rs:45]: The main reason parse_no_hint exists is to provide compatibility with the pre-existing tests, but since it's a crate only function, it can safely be removed.

Comment (wojciechkepka) [reply src/headers/exth.rs:45]: DEFAULT_EXTH_OFFSET sounds alright, and it does seem like your right about the offset that will make it more readable.

Comment (philippeitis) [reply src/headers/exth.rs]: On the other hand, passing in a default value is unsafe, and is what caused the issue in the first place. It also doesn't demonstrate robust usage of the library - getting rid of the value and parse_no_hint entirely seems to be a better choice, since we can just replace

```rust
                let exth = ExtHeader::parse_no_hint(&mut reader).unwrap();
```
with

```rust
                let mobi = MobiHeader::parse(&mut reader).unwrap();
                let exth = ExtHeader::parse(&mut reader, mobi.header_length).unwrap();
```
and have safe usage.

Comment (wojciechkepka) [reply src/headers/exth.rs]: Actually, i guess the parse_no_hint can completely go away because mobi header is of variable length and there is no such think as default exth offset. So I would leave `const RECORDS_OFFSET: u16 = 108;` and i would get rid of `parse_no_hint`.

Comment (wojciechkepka) [reply src/headers/exth.rs]: I didn't see your comment before i've sent mine but I guess we are on the same side :+1:

**Comment by wojciechkepka** [comment]
Thanks for all the work :) I'll try to release a fixed version soon. I want to include some more changes.
